const mongoose = require("mongoose");

// Schema for storing payment transactions
const PaymentSchema = new mongoose.Schema({
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: "User", 
    required: true // Reference to the user making the payment
  },
  orderId: { 
    type: String, 
    required: true // Order ID generated by Razorpay
  },
  paymentId: { 
    type: String // Payment ID returned by Razorpay (can be updated after verification)
  },
  amount: { 
    type: Number, 
    required: true // Payment amount in smallest currency unit (e.g., paisa for INR)
  },
  currency: { 
    type: String, 
    default: "INR" // Currency type, default is INR
  },
  status: { 
    type: String, 
    enum: ["created", "paid", "failed"], 
    default: "created" // Payment status
  },
  receipt: { 
    type: String // Receipt details if available
  },
  notes: { 
    type: String // Any additional notes related to the payment
  }
}, { timestamps: true }); // Automatically adds createdAt and updatedAt fields

module.exports = mongoose.model("Payment", PaymentSchema);
